# Generated by Django 4.2.2 on 2023-10-07 16:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("service_catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Execution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exec_id",
                    models.UUIDField(
                        default=uuid.uuid4, help_text="Execution unique ID", unique=True
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Created"),
                            (1, "Source Success"),
                            (2, "Source Failed"),
                            (3, "Dest Failed"),
                            (4, "Completed"),
                        ],
                        default=0,
                        help_text="Status",
                    ),
                ),
                (
                    "start_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Start of activity"
                    ),
                ),
                ("last_updated", models.DateTimeField(null=True)),
                ("finished_at", models.DateTimeField(help_text="End of activity")),
                ("note", models.CharField(max_length=50, null=True)),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exec_policy",
                        to="service_catalog.policy",
                    ),
                ),
            ],
        ),
    ]
