# Generated by Django 4.2.2 on 2023-10-07 16:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("archive_auth", "0002_remove_archiveuser_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="archiveuser",
            name="is_admin",
        ),
    ]
