# Generated by Django 4.2.2 on 2023-10-08 05:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archive_auth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="archiveuser",
            name="unique_id",
            field=models.CharField(
                default="test", max_length=30, unique=True, verbose_name="Username"
            ),
        ),
    ]
