# Generated by Django 4.2.2 on 2023-10-08 06:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("service_catalog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="policy",
            name="service",
        ),
        migrations.RemoveField(
            model_name="policy",
            name="source_db",
        ),
        migrations.RemoveField(
            model_name="policy",
            name="source_schema",
        ),
    ]
